### ISSUE TITLE
sistemadeviajes.py

### ISSUE THREAD

**Issue by dieguit** [pointtonull/carmensandiego#1]
Che esta bueno el code.. pero me salen errores de sintaxis en los print..
Los solucione reemplazando:
print 'Viajando desde %s' %(origen,)
por:
print ('Viajando desde %s' %(origen,))

Otra cosa.. despues de esto el programa ya se ejecuta pero me salta esto (pego la salida completa del programa):

"""""""""""""""""""""

Ciudades:
[1] : Buenos Aires

[2] : Santiago de Chile

[3] : Nueva York

"""""""""""""""""""""

Traceback (most recent call last):
  File "D:\Proyectos\git\sistemadeviajes.py", line 73, in <module>
    main()
  File "D:\Proyectos\git\sistemadeviajes.py", line 56, in main
    o = raw_input('Elige origen : ')
NameError: global name 'raw_input' is not defined

y se corta la ejecucion..
Ahora estoy ejecutando esto desde Windows..
Que dicen??

**Comment by dieguit** [comment]
Solucionado matias! era que estaba con python 3.1!

**Comment by pointtonull** [comment]
Esto es, aparentemente, un problema de versiones. Creo que deberemos usar la rama 2.6 para darle más facilidad de ejecución en distintas plataformas. Plus, es trivial pasar a versiones más recientes.

Saludos
