### ISSUE TITLE
unable to gather evidence

### ISSUE THREAD

**Issue by petroleumjelliffe** [pointtonull/carmensandiego#2]
Nothing happens after you Gather Evidence or Search for witnesses in Options.  The image changes, but none of the buttons besides "options" does anything.

**Comment by pointtonull** [comment]
Hi!
I'm afraid that this project was just a draft we never started to code seriously.
:-(

**Comment by cadilhe** [comment]
How to run the draft of this project?

**Comment by mattgaviota** [comment]
Just do python sistemadeviajes.py
